### ISSUE TITLE
Question:  compatibility with es6 getters

### ISSUE THREAD

**Issue by danielspaniel** [ember-decorators/auto-computed#3]
While I, of course, love this addon, and the style of computed it offers:

 If I do this:
```js
export default class ExampleComponent extends Component {
  @autoComputed('someKey', 'otherKey')
  bar(someKey, otherKey) {
    return `${someKey} - ${otherKey}`;
  }
}
```
Is this going to be compatible with the way ember is removing the need for using get to call a computed property?
In other words, if I use auto-computed style will I be able to do:
```js
this.bar 
```
within the component or will I be forced to do: 
```js
this.get('bar'); 
```

**Comment by pzuraq** [comment]
Once the RFC is merged, the plan is to update both this library and `ember-decorators` to automatically provide `this.bar` style getters. This should be backwards compatible as well, so it'll work all the way back to Ember 1.11 😄

**Comment by danielspaniel** [comment]
Wow .. ok .. that is music to the ears .. thanks a mucho lot. 👯
