### ISSUE TITLE
ember 3.1.0 beta breaks auto computed

### ISSUE THREAD

**Issue by danielspaniel** [ember-decorators/auto-computed#5]
I could submit a PR, but all you have to do is update package of ember-source to 3.1.0-beta.4 and the test 
> auto computed properties: dependent key changes invalidate the computed property 
fails .. 

 I am available all weekend to help fix it. 😄 

I bumped up @ember-decorators/utils  to 2.0.0-beta.4  and that has a few differences ( like no more extractValue ) .. so have been noodling around with that update in this repo as well  ( which I think is necessary too )

**Comment by danielspaniel** [comment]
@pzuraq .. any idea if this can be fixed? .. or how i can help

**Comment by pzuraq** [comment]
it should be possible using the new `@ember-decorators/utils`, I don't think conceptually anything has changed too much. I haven't had time to dive in, I'll be focussing on finishing up `ember-decorators@v2` during my OSS time this week, but may be able to get to in next week.

**Comment by danielspaniel** [comment]
ok .. let me know if you want any help ( i might need pointers )  .. currently the auto computed delegates the work to macroComputed  ( ember-macro-helpers ) so that is the thing that is broken

**Comment by pzuraq** [comment]
Would love some help 😄 I'm available on Slack or here if you have any questions or need help getting started

**Comment by danielspaniel** [comment]
@pzuraq I submitted a PR for the fix for 3.1

**Comment by danielspaniel** [comment]
v2.0.0 has this fix
